# Aula 02 - Python

#### Dados Númericos

In [1]:
# Variável Inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [2]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [3]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [4]:
# Declarando NaN
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [5]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


#### Dados de Texto

In [6]:
# Declaração de variável texto
f = 'Fábio'
g = 'Gabriel'
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


#### Dados do tipo bool - lógica

In [7]:
a == 1

True

In [8]:
h = (a==1)
print(h)
type(h)

True


bool

In [9]:
h = (a==2)
print(h)
type(h)

False


bool

In [10]:
i = True
type(i)

bool

In [12]:
ii = 'True'
type(ii)

str

#### Operações de comparação

In [13]:
# Operação ==
a==b

True

In [14]:
# Operação ><
a>b

False

In [15]:
# Operação !=
a!=b

False

In [16]:
# Operação >= ou <=
a>=b

True

#### Operações Matemáticas

In [17]:
# Soma
a+b

2.0

In [18]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [20]:
#Multiplicação
l = a*b # Não use l como variável
print('Nã use l como nome de variável')
j = a*b
print(j)

Nã use l como nome de variável
1.0


In [21]:
#Divisão
a/b

1.0

In [22]:
#Potência
5**2

25

In [23]:
#Operações matemáticas com a biblioteca math
import math
math.exp(10)

22026.465794806718

In [24]:
math.exp(0)

1.0

In [25]:
math.exp(a)

2.718281828459045

In [26]:
math.exp(-10)

4.5399929762484854e-05

In [27]:
import math as mt
mt.log(c)

0.0

In [28]:
mt.log10(100)

2.0

#### Listas

In [29]:
myfirstlist = [1,2,3]
print(myfirstlist)

[1, 2, 3]


In [32]:
#Acessando os valores da lita pelo index
print(myfirstlist[0])
print(myfirstlist[2])

1
3


In [33]:
myfirstlist==a

False

In [35]:
myfirstlist[0]==a

True

In [37]:
myseclist = [1,a,'c']
print(myseclist)

[1, 1, 'c']


In [38]:
type(myseclist)

list

In [39]:
type(myseclist[2])

str

In [40]:
type(myseclist[1])

int

#### Caminhos = path

In [42]:
path = r"C:\Users\HP\Documents\Gabriel.py\ENS5173"
print(path)

C:\Users\HP\Documents\Gabriel.py\ENS5173


In [43]:
import os
# listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [44]:
# selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [49]:
# concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:\\Users\\HP\\Documents\\Gabriel.py\\ENS5173/.git'

In [50]:
# listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])


['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [51]:
#Diretório que estou trabalhando
os.getcwd()

'C:\\Users\\HP\\Documents\\Gabriel.py\\ENS5173\\venv\\Scripts'

In [52]:
# Mudando o diretório de caminho
os.chdir('C:\\Users\\HP\\Documents')

In [53]:
os.getcwd()

'C:\\Users\\HP\\Documents'

In [55]:
#Criando novo diretório
new_path = os.getcwd()+'/test'
if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('criando diretório '+new_path)
    os.mkdir(new_path)

criando diretório C:\Users\HP\Documents/test


In [61]:
#criando novo diretório
new_path = os.getcwd()+'/test2'
if os.path.isdir(new_path):
    print('diretório já existe')
    #criando um arquivo texto
    with open(new_path+'/copy.txt','w') as file:
        file.write("your text goes here")
else:
    print('criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+'/copy.txt','w') as file:
        file.write('your text goes here')
         
    

diretório já existe


#### Numpy arrays e Pandas Dataframes

In [62]:
import numpy as np
#criando uma variável numpy
n=np.array(0)
type(n)

numpy.ndarray

In [63]:
#criando uma variável numpy a partir de uma lista
mythirdlist=[1,2,3,10,20,55]
n = np.array(mythirdlist)
print(n)

[ 1  2  3 10 20 55]


In [64]:
#criando matriz 10x10 de números aleatórios entre 0 e 1
n=np.random.rand(10,10)
print(n)
#dimensões da matriz
print(n.shape)

[[0.39636941 0.53200493 0.07985733 0.99502837 0.6928126  0.06112197
  0.97155359 0.04125765 0.83492222 0.69869948]
 [0.28653817 0.44527192 0.74407322 0.33577849 0.2401191  0.59021414
  0.14351504 0.81085979 0.58024986 0.40232625]
 [0.29394872 0.7333551  0.71626853 0.83029194 0.67606941 0.65675545
  0.25336811 0.77752871 0.44650095 0.7511076 ]
 [0.98398485 0.78745104 0.92997716 0.18888204 0.11269435 0.79153477
  0.61845125 0.23094779 0.30332268 0.49811784]
 [0.00487401 0.64858404 0.14439012 0.60020709 0.26360593 0.47397926
  0.25822928 0.11663368 0.86555405 0.13720366]
 [0.66039407 0.90403348 0.01359413 0.3318233  0.73585337 0.293174
  0.04621798 0.97736525 0.14871961 0.4872754 ]
 [0.43894035 0.38708235 0.96227636 0.45792659 0.14148057 0.55884025
  0.66718534 0.45882621 0.8796958  0.18994969]
 [0.91009673 0.96858897 0.80380184 0.65971229 0.51217939 0.30291759
  0.41180483 0.88543776 0.23628521 0.21047638]
 [0.67769031 0.23662433 0.02264101 0.68914398 0.68450279 0.57336227
  0.95644891 0

In [65]:
#acessando valores da matriz
n[:,0]

array([0.39636941, 0.28653817, 0.29394872, 0.98398485, 0.00487401,
       0.66039407, 0.43894035, 0.91009673, 0.67769031, 0.30377887])

In [66]:
n[0,:]

array([0.39636941, 0.53200493, 0.07985733, 0.99502837, 0.6928126 ,
       0.06112197, 0.97155359, 0.04125765, 0.83492222, 0.69869948])

In [67]:
n[:,1:5]

array([[0.53200493, 0.07985733, 0.99502837, 0.6928126 ],
       [0.44527192, 0.74407322, 0.33577849, 0.2401191 ],
       [0.7333551 , 0.71626853, 0.83029194, 0.67606941],
       [0.78745104, 0.92997716, 0.18888204, 0.11269435],
       [0.64858404, 0.14439012, 0.60020709, 0.26360593],
       [0.90403348, 0.01359413, 0.3318233 , 0.73585337],
       [0.38708235, 0.96227636, 0.45792659, 0.14148057],
       [0.96858897, 0.80380184, 0.65971229, 0.51217939],
       [0.23662433, 0.02264101, 0.68914398, 0.68450279],
       [0.00124698, 0.30006483, 0.61446928, 0.78444986]])

In [68]:
n[0,1:5]

array([0.53200493, 0.07985733, 0.99502837, 0.6928126 ])

In [69]:
n[0,-1]

0.6986994800216958

In [70]:
n[0,4:-1]

array([0.6928126 , 0.06112197, 0.97155359, 0.04125765, 0.83492222])

In [71]:
n[0,4:]

array([0.6928126 , 0.06112197, 0.97155359, 0.04125765, 0.83492222,
       0.69869948])

In [72]:
an = np.log(n*5)
print(an)

[[ 0.68402925  0.97833538 -0.91807573  1.60445388  1.24244217 -1.18544602
   1.58057907 -1.5784808   1.4290212   1.25090335]
 [ 0.35955438  0.80036778  1.31382208  0.51813433  0.1828177   1.08216805
  -0.33187756  1.39977779  1.06514144  0.69894597]
 [ 0.38508797  1.29931266  1.27573777  1.42346001  1.21797838  1.18899436
   0.23652604  1.3578032   0.80312417  1.32323155]
 [ 1.59329314  1.37048383  1.53684266 -0.05719465 -0.57363807  1.37565644
   1.12890101  0.14387428  0.41647982  0.91251932]
 [-3.71440053  1.17647421 -0.32579856  1.09895737  0.27613795  0.86284621
   0.2555305  -0.5392793   1.46505246 -0.376851  ]
 [ 1.19451937  1.50854903 -2.68867959  0.50628522  1.30271351  0.38244893
  -1.46494842  1.58654307 -0.29625463  0.8905121 ]
 [ 0.78604616  0.66032011  1.57098432  0.82839152 -0.34615498  1.02754629
   1.20475052  0.83035415  1.4812588  -0.05155812]
 [ 1.51523353  1.57752298  1.3910354   1.19348645  0.94035757  0.41514344
   0.72223217  1.4877648   0.16672223  0.05105607]
